import { Injectable } from '@angular/core';
import { Card } from '../interfaces/card';

@Injectable({
  providedIn: 'root',
})
export class CardService {
  private gameCards: Array<Card> = [
    // Animals
    {
      categoryId: 1,
      name: 'Cat',
      translation: 'კატა',
      imageUrl: '../../assets/cards/animals/cat.png',
      audioSrc: '../../../assets/audio/animals/Cat.mp3',
    },
    {
      categoryId: 1,
      name: 'Dog',
      translation: 'ძაღლი',
      imageUrl: '../../assets/cards/animals/dog.png',
      audioSrc: '../../../assets/audio/animals/Dog.mp3',
    },
    {
      categoryId: 1,
      name: 'Cow',
      translation: 'ძროხა',
      imageUrl: '../../assets/cards/animals/cow.png',
      audioSrc: '../../../assets/audio/animals/Cow.mp3',
    },
    {
      categoryId: 1,
      name: 'Horse',
      translation: 'ცხენი',
      imageUrl: '../../assets/cards/animals/horse.png',
      audioSrc: '../../../assets/audio/animals/Horse.mp3',
    },
    {
      categoryId: 1,
      name: 'Pig',
      translation: 'ღორი',
      imageUrl: '../../assets/cards/animals/pig.png',
      audioSrc: '../../../assets/audio/animals/Pig.mp3',
    },
    {
      categoryId: 1,
      name: 'Rabbit',
      translation: 'კურდღელი',
      imageUrl: '../../assets/cards/animals/rabbit.png',
      audioSrc: '../../../assets/audio/animals/Rabbit.mp3',
    },
    {
      categoryId: 1,
      name: 'Elephant',
      translation: 'სპილო',
      imageUrl: '../../assets/cards/animals/elephant.png',
      audioSrc: '../../../assets/audio/animals/Elephant.mp3',
    },
    {
      categoryId: 1,
      name: 'Sheep',
      translation: 'ცხვარი',
      imageUrl: '../../assets/cards/animals/sheep.png',
      audioSrc: '../../../assets/audio/animals/Sheep.mp3',
    },
    {
      categoryId: 1,
      name: 'Giraffe',
      translation: 'ჟირაფი',
      imageUrl: '../../assets/cards/animals/giraffe.png',
      audioSrc: '../../../assets/audio/animals/Giraffe.mp3',
    },
    {
      categoryId: 1,
      name: 'Panda',
      translation: 'პანდა',
      imageUrl: '../../assets/cards/animals/panda.png',
      audioSrc: '../../../assets/audio/animals/Panda.mp3',
    },
    {
      categoryId: 1,
      name: 'Lion',
      translation: 'ლომი',
      imageUrl: '../../assets/cards/animals/lion.png',
      audioSrc: '../../../assets/audio/animals/Lion.mp3',
    },
    {
      categoryId: 1,
      name: 'Bear',
      translation: 'დათვი',
      imageUrl: '../../assets/cards/animals/bear.png',
      audioSrc: '../../../assets/audio/animals/Bear.mp3',
    },
    {
      categoryId: 1,
      name: 'Zebra',
      translation: 'ზებრა',
      imageUrl: '../../assets/cards/animals/zebra.png',
      audioSrc: '../../../assets/audio/animals/Zebra.mp3',
    },
    {
      categoryId: 1,
      name: 'Tiger',
      translation: 'ვეფხვი',
      imageUrl: '../../assets/cards/animals/tiger.png',
      audioSrc: '../../../assets/audio/animals/Tiger.mp3',
    },
    {
      categoryId: 1,
      name: 'Fox',
      translation: 'მელია',
      imageUrl: '../../assets/cards/animals/fox.png',
      audioSrc: '../../../assets/audio/animals/Fox.mp3'
    },
    {
      categoryId: 1,
      name: 'Wolf',
      translation: 'მგელი',
      imageUrl: '../../assets/cards/animals/wolf.png',
      audioSrc: '../../../assets/audio/animals/Wolf.mp3',
    },
    {
      categoryId: 1,
      name: 'Monkey',
      translation: 'მაიმუნი',
      imageUrl: '../../assets/cards/animals/monkey.png',
      audioSrc: '../../../assets/audio/animals/Monkey.mp3',
    },
    // Birds
    {
      categoryId: 2,
      name: 'Chicken',
      translation: 'ქათამი',
      imageUrl: '../../assets/cards/birds/chicken.png',
      audioSrc: '../../../assets/audio/birds/Chicken.mp3',
    },
    {
      categoryId: 2,
      name: 'Dove',
      translation: 'მტრედი',
      imageUrl: '../../assets/cards/birds/dove.png',
      audioSrc: '../../../assets/audio/birds/Dove.mp3',
    },
    {
      categoryId: 2,
      name: 'Duck',
      translation: 'იხვი',
      imageUrl: '../../assets/cards/birds/duck.png',
      audioSrc: '../../../assets/audio/birds/Duck.mp3',
    },
    {
      categoryId: 2,
      name: 'Falcon',
      translation: 'შავარდენი',
      imageUrl: '../../assets/cards/birds/falcon.png',
      audioSrc: '../../../assets/audio/birds/Falcon.mp3',
    },
    {
      categoryId: 2,
      name: 'Flamingo',
      translation: 'ფლამინგო',
      imageUrl: '../../assets/cards/birds/flamingo.png',
      audioSrc: '../../../assets/audio/birds/Flamingo.mp3',
    },
    {
      categoryId: 2,
      name: 'Goose',
      translation: 'ბატი',
      imageUrl: '../../assets/cards/birds/goose.png',
      audioSrc: '../../../assets/audio/birds/Goose.mp3',
    },
    {
      categoryId: 2,
      name: 'Owl',
      translation: 'ბუ',
      imageUrl: '../../assets/cards/birds/owl.png',
      audioSrc: '../../../assets/audio/birds/Owl.mp3',
    },
    {
      categoryId: 2,
      name: 'Parrot',
      translation: 'თუთიყუში',
      imageUrl: '../../assets/cards/birds/parrot.png',
      audioSrc: '../../../assets/audio/birds/Parrot.mp3',
    },
    {
      categoryId: 2,
      name: 'Hummingbird',
      translation: 'კოლიბრი',
      imageUrl: '../../assets/cards/birds/humming-bird.png',
      audioSrc: '../../../assets/audio/birds/Hummingbird.mp3',
    },
    {
      categoryId: 2,
      name: 'Pelican',
      translation: 'ვარხვი',
      imageUrl: '../../assets/cards/birds/pelican.png',
      audioSrc: '../../../assets/audio/birds/Pelican.mp3',
    },
    {
      categoryId: 2,
      name: 'Stork',
      translation: 'ყარყატი',
      imageUrl: '../../assets/cards/birds/stork.png',
      audioSrc: '../../../assets/audio/birds/Stork.mp3',
    },
    {
      categoryId: 2,
      name: 'Swan',
      translation: 'გედი',
      imageUrl: '../../assets/cards/birds/swan.png',
      audioSrc: '../../../assets/audio/birds/Swan.mp3',
    },
    {
      categoryId: 2,
      name: 'Eagle',
      translation: 'არწივი',
      imageUrl: '../../assets/cards/birds/eagle.png',
      audioSrc: '../../../assets/audio/birds/Eagle.mp3',
    },
    // Colors
    {
      categoryId: 3,
      name: 'White',
      translation: 'თეთრი',
      imageUrl: '../../assets/cards/colors/white.png',
      audioSrc: '../../../assets/audio/colors/White.mp3',
    },
    {
      categoryId: 3,
      name: 'Yellow',
      translation: 'ყვითელი',
      imageUrl: '../../assets/cards/colors/yellow.png',
      audioSrc: '../../../assets/audio/colors/Colors.mp3',
    },
    {
      categoryId: 3,
      name: 'Orange',
      translation: 'ნარინჯისფერი',
      imageUrl: '../../assets/cards/colors/orange.png',
      audioSrc: '../../../assets/audio/colors/Orange.mp3',
    },
    {
      categoryId: 3,
      name: 'Red',
      translation: 'წითელი',
      imageUrl: '../../assets/cards/colors/red.png',
      audioSrc: '../../../assets/audio/colors/Red.mp3',
    },
    {
      categoryId: 3,
      name: 'Green',
      translation: 'მწვანე',
      imageUrl: '../../assets/cards/colors/green.png',
      audioSrc: '../../../assets/audio/colors/Green.mp3',
    },
    {
      categoryId: 3,
      name: 'Cyan',
      translation: 'ცისფერი',
      imageUrl: '../../assets/cards/colors/cyan.png',
      audioSrc: '../../../assets/audio/colors/Cyan.mp3',
    },
    {
      categoryId: 3,
      name: 'Blue',
      translation: 'ლურჯი',
      imageUrl: '../../assets/cards/colors/blue.png',
      audioSrc: '../../../assets/audio/colors/Blue.mp3',
    },
    {
      categoryId: 3,
      name: 'Purple',
      translation: 'იისფერი',
      imageUrl: '../../assets/cards/colors/purple.png',
      audioSrc: '../../../assets/audio/colors/Purple.mp3',
    },
    {
      categoryId: 3,
      name: 'Brown',
      translation: 'ყავისფერი',
      imageUrl: '../../assets/cards/colors/brown.png',
      audioSrc: '../../../assets/audio/colors/Brown.mp3',
    },
    {
      categoryId: 3,
      name: 'Black',
      translation: 'შავი',
      imageUrl: '../../assets/cards/colors/black.png',
      audioSrc: '../../../assets/audio/colors/Black.mp3',
    },
    {
      categoryId: 3,
      name: 'Rainbow',
      translation: 'ცისარტყელა',
      imageUrl: '../../assets/cards/colors/rainbow.png',
      audioSrc: '../../../assets/audio/colors/Rainbow.mp3',
    },
    // Body
    {
      categoryId: 4,
      name: 'Body',
      translation: 'სხეული',
      imageUrl: '../../assets/cards/body/body.png',
      audioSrc: '../../../assets/audio/body/Body.mp3',
    },
    {
      categoryId: 4,
      name: 'Head',
      translation: 'თავი',
      imageUrl: '../../assets/cards/body/head.png',
      audioSrc: '../../../assets/audio/body/Head.mp3',
    },
    {
      categoryId: 4,
      name: 'Chest',
      translation: 'მკერდი',
      imageUrl: '../../assets/cards/body/chest.png',
      audioSrc: '../../../assets/audio/body/Chest.mp3',
    },
    {
      categoryId: 4,
      name: 'Back',
      translation: 'ზურგი',
      imageUrl: '../../assets/cards/body/back.png',
      audioSrc: '../../../assets/audio/body/Back.mp3',
    },
    {
      categoryId: 4,
      name: 'Nose',
      translation: 'ცხვირი',
      imageUrl: '../../assets/cards/body/nose.png',
      audioSrc: '../../../assets/audio/body/Nose.mp3',
    },
    {
      categoryId: 4,
      name: 'Eyes',
      translation: 'თვალები',
      imageUrl: '../../assets/cards/body/eyes.png',
      audioSrc: '../../../assets/audio/body/Eyes.mp3',
    },
    {
      categoryId: 4,
      name: 'Chin',
      translation: 'ნიკაპი',
      imageUrl: '../../assets/cards/body/chin.png',
      audioSrc: '../../../assets/audio/body/Chin.mp3',
    },
    {
      categoryId: 4,
      name: 'Ear',
      translation: 'ყური',
      imageUrl: '../../assets/cards/body/ear.png',
      audioSrc: '../../../assets/audio/body/Ears.mp3',
    },
    {
      categoryId: 4,
      name: 'Lips',
      translation: 'ტუჩები',
      imageUrl: '../../assets/cards/body/lips.png',
      audioSrc: '../../../assets/audio/body/Lips.mp3',
    },
    {
      categoryId: 4,
      name: 'Fingers',
      translation: 'თითები',
      imageUrl: '../../assets/cards/body/fingers.png',
      audioSrc: '../../../assets/audio/body/Fingers.mp3',
    },
    {
      categoryId: 4,
      name: 'Hand',
      translation: 'ხელი',
      imageUrl: '../../assets/cards/body/hand.png',
      audioSrc: '../../../assets/audio/body/Hand.mp3',
    },
    {
      categoryId: 4,
      name: 'Elbow',
      translation: 'იდაყვი',
      imageUrl: '../../assets/cards/body/elbow.png',
      audioSrc: '../../../assets/audio/body/Elbow.mp3',
    },
    {
      categoryId: 4,
      name: 'Ankle',
      translation: 'კოჭი',
      imageUrl: '../../assets/cards/body/ankle.png',
      audioSrc: '../../../assets/audio/body/Ankle.mp3',
    },
    {
      categoryId: 4,
      name: 'Leg',
      translation: 'მუხლი',
      imageUrl: '../../assets/cards/body/leg.png',
      audioSrc: '../../../assets/audio/body/Leg.mp3',
    },
    // Home
    {
      categoryId: 5,
      name: 'Bed',
      translation: 'საწოლი',
      imageUrl: '../../assets/cards/home/bed.png',
      audioSrc: '../../../assets/audio/home/Bed.mp3',
    },
    {
      categoryId: 5,
      name: 'Armchair',
      translation: 'სავარძელი',
      imageUrl: '../../assets/cards/home/armchair.png',
      audioSrc: '../../../assets/audio/home/Armchair.mp3',
    },
    {
      categoryId: 5,
      name: 'Sofa',
      translation: 'დივანი',
      imageUrl: '../../assets/cards/home/sofa.png',
      audioSrc: '../../../assets/audio/home/Sofa.mp3',
    },
    {
      categoryId: 5,
      name: 'Chair',
      translation: 'სკამი',
      imageUrl: '../../assets/cards/home/chair.png',
      audioSrc: '../../../assets/audio/home/Chair.mp3',
    },
    {
      categoryId: 5,
      name: 'Wardrobe',
      translation: 'გარდერობი',
      imageUrl: '../../assets/cards/home/wardrobe.png',
      audioSrc: '../../../assets/audio/home/Wardrobe.mp3',
    },
    {
      categoryId: 5,
      name: 'Bookcase',
      translation: 'წიგნთსაცავი',
      imageUrl: '../../assets/cards/home/bookcase.png',
      audioSrc: '../../../assets/audio/home/Bookcase.mp3',
    },
    {
      categoryId: 5,
      name: 'Bath',
      translation: 'აბაზანა',
      imageUrl: '../../assets/cards/home/bath.png',
      audioSrc: '../../../assets/audio/home/Bath.mp3',
    },
    {
      categoryId: 5,
      name: 'Fridge',
      translation: 'მაცივარი',
      imageUrl: '../../assets/cards/home/fridge.png',
      audioSrc: '../../../assets/audio/home/Fridge.mp3',
    },
    {
      categoryId: 5,
      name: 'Teapot',
      translation: 'ჩაიდანი',
      imageUrl: '../../assets/cards/home/electric-teapot.png',
      audioSrc: '../../../assets/audio/home/Teapot.mp3',
    },
    {
      categoryId: 5,
      name: 'Vacuum Cleaner',
      translation: 'მტვერსასრუტი',
      imageUrl: '../../assets/cards/home/vacuum-cleaner.png',
      audioSrc: '../../../assets/audio/home/Vacuum Cleaner.mp3',
    },
    {
      categoryId: 5,
      name: 'Washing Machine',
      translation: 'სარეცხის მანქანა',
      imageUrl: '../../assets/cards/home/washing-machine.png',
      audioSrc: '../../../assets/audio/home/Washing Machine.mp3',
    },
    // Family
    {
      categoryId: 6,
      name: 'Mother',
      translation: 'დედა',
      imageUrl: '../../assets/cards/family/mother.png',
      audioSrc: '../../../assets/audio/family/Mother.mp3',
    },
    {
      categoryId: 6,
      name: 'Father',
      translation: 'მამა',
      imageUrl: '../../assets/cards/family/father.png',
      audioSrc: '../../../assets/audio/family/Father.mp3',
    },
    {
      categoryId: 6,
      name: 'Son/Boy',
      translation: 'ვაჟიშვილი/ბიჭი',
      imageUrl: '../../assets/cards/family/boy-son.png',
      audioSrc: '../../../assets/audio/family/Son-Boy.mp3',
    },
    {
      categoryId: 6,
      name: 'Daughter/Girl',
      translation: 'ქალიშვილი/გოგონა',
      imageUrl: '../../assets/cards/family/girl-daughter.png',
      audioSrc: '../../../assets/audio/family/Daughter-Girl.mp3',
    },
    {
      categoryId: 6,
      name: 'Grandmother',
      translation: 'ბებია',
      imageUrl: '../../assets/cards/family/grandma.png',
      audioSrc: '../../../assets/audio/family/Grandmother.mp3',
    },
    {
      categoryId: 6,
      name: 'Grandfather',
      translation: 'ბაბუა',
      imageUrl: '../../assets/cards/family/grandpa.png',
      audioSrc: '../../../assets/audio/family/Grandfather.mp3',
    },
    {
      categoryId: 6,
      name: 'Aunt',
      translation: 'დეიდა/მამიდა',
      imageUrl: '../../assets/cards/family/woman-aunt.png',
      audioSrc: '../../../assets/audio/family/Aunt.mp3',
    },
    {
      categoryId: 6,
      name: 'Uncle',
      translation: 'ბიძა',
      imageUrl: '../../assets/cards/family/man-uncle.png',
      audioSrc: '../../../assets/audio/family/Uncle.mp3',
    },
    // Weather
    {
      categoryId: 7,
      name: 'Sunny',
      translation: 'მზიანი',
      imageUrl: '../../assets/cards/weather/sunny.png',
      audioSrc: '../../../assets/audio/weather/Sunny.mp3',
    },
    {
      categoryId: 7,
      name: 'Cloudiness',
      translation: 'ღრუბლიანობა',
      imageUrl: '../../assets/cards/weather/cloudiness.png',
      audioSrc: '../../../assets/audio/weather/Cloudiness.mp3',
    },
    {
      categoryId: 7,
      name: 'Wind',
      translation: 'ქარი',
      imageUrl: '../../assets/cards/weather/wind.png',
      audioSrc: '../../../assets/audio/weather/Wind.mp3',
    },
    {
      categoryId: 7,
      name: 'Rain',
      translation: 'წვიმა',
      imageUrl: '../../assets/cards/weather/rain.png',
      audioSrc: '../../../assets/audio/weather/Rain.mp3',
    },
    {
      categoryId: 7,
      name: 'Hail',
      translation: 'სეტყვა',
      imageUrl: '../../assets/cards/weather/hail.png',
      audioSrc: '../../../assets/audio/weather/Hail.mp3',
    },
    {
      categoryId: 7,
      name: 'Storm',
      translation: 'ქარიშხალი',
      imageUrl: '../../assets/cards/weather/storm.png',
      audioSrc: '../../../assets/audio/weather/Storm.mp3',
    },
    {
      categoryId: 7,
      name: 'Snow',
      translation: 'თოვლი',
      imageUrl: '../../assets/cards/weather/snow.png',
      audioSrc: '../../../assets/audio/weather/Snow.mp3',
    },
    {
      categoryId: 7,
      name: 'Lightning',
      translation: 'ბიძა',
      imageUrl: '../../assets/cards/weather/lightning.png',
      audioSrc: '../../../assets/audio/weather/Ligntning.mp3',
    },
    {
      categoryId: 7,
      name: 'Fog',
      translation: 'ნისლი',
      imageUrl: '../../assets/cards/weather/fog.png',
      audioSrc: '../../../assets/audio/weather/Fog.mp3',
    },
    // Seasons
    {
      categoryId: 8,
      name: 'Winter',
      translation: 'ზამთარი',
      imageUrl: '../../assets/cards/seasons/winter.png',
      audioSrc: '../../../assets/audio/seasons/Winter.mp3',

    },
    {
      categoryId: 8,
      name: 'Spring',
      translation: 'გაზაფხული',
      imageUrl: '../../assets/cards/seasons/spring.png',
      audioSrc: '../../../assets/audio/seasons/Spring.mp3',
    },
    {
      categoryId: 8,
      name: 'Summer',
      translation: 'ზაფხული',
      imageUrl: '../../assets/cards/seasons/summer.png',
      audioSrc: '../../../assets/audio/seasons/Summer.mp3',
    },
    {
      categoryId: 8,
      name: 'Autumn',
      translation: 'შემოდგომა',
      imageUrl: '../../assets/cards/seasons/autumn.png',
      audioSrc: '../../../assets/audio/seasons/Autumn.mp3',
    },
    // Fruits
    {
      categoryId: 9,
      name: 'Apple',
      translation: 'ვაშლი',
      imageUrl: '../../assets/cards/fruits/apple.png',
      audioSrc: '../../../assets/audio/fruits/Apple.mp3',
    },
    {
      categoryId: 9,
      name: 'Pear',
      translation: 'მსხალი',
      imageUrl: '../../assets/cards/fruits/pear.png',
      audioSrc: '../../../assets/audio/fruits/Pear.mp3',
    },
    {
      categoryId: 9,
      name: 'Peach',
      translation: 'ატამი',
      imageUrl: '../../assets/cards/fruits/peach.png',
      audioSrc: '../../../assets/audio/fruits/Peach.mp3',
    },
    {
      categoryId: 9,
      name: 'Apricot',
      translation: 'გარგარი',
      imageUrl: '../../assets/cards/fruits/apricot.png',
      audioSrc: '../../../assets/audio/fruits/Apricot.mp3',
    },
    {
      categoryId: 9,
      name: 'Banana',
      translation: 'ბანანი',
      imageUrl: '../../assets/cards/fruits/banana.png',
      audioSrc: '../../../assets/audio/fruits/Banana.mp3',
    },
    {
      categoryId: 9,
      name: 'Clementine',
      translation: 'მანდარინი',
      imageUrl: '../../assets/cards/fruits/clementine.png',
      audioSrc: '../../../assets/audio/fruits/Clementine.mp3',
    },
    {
      categoryId: 9,
      name: 'Orange',
      translation: 'ფორთოხალი',
      imageUrl: '../../assets/cards/fruits/orange.png',
      audioSrc: '../../../assets/audio/fruits/Orange.mp3',
    },
    {
      categoryId: 9,
      name: 'Tangelo',
      translation: 'გრეიპფრუტი',
      imageUrl: '../../assets/cards/fruits/tangelo.png',
      audioSrc: '../../../assets/audio/fruits/Tangelo.mp3',
    },
    {
      categoryId: 9,
      name: 'Lemon',
      translation: 'ლიმონი',
      imageUrl: '../../assets/cards/fruits/lemon.png',
      audioSrc: '../../../assets/audio/fruits/Lemon.mp3',
    },
    {
      categoryId: 9,
      name: 'Avocado',
      translation: 'ავოკადო',
      imageUrl: '../../assets/cards/fruits/avocado.png',
      audioSrc: '../../../assets/audio/fruits/Avocado.mp3',
    },
    {
      categoryId: 9,
      name: 'Cherry',
      translation: 'ალუბალი',
      imageUrl: '../../assets/cards/fruits/cherry.png',
      audioSrc: '../../../assets/audio/fruits/Cherry.mp3',
    },
    {
      categoryId: 9,
      name: 'Pomegranate',
      translation: 'ბროწეული',
      imageUrl: '../../assets/cards/fruits/pomegranate.png',
      audioSrc: '../../../assets/audio/fruits/Pomegranate.mp3',
    },
    {
      categoryId: 9,
      name: 'Strawberry',
      translation: 'მარწყვი',
      imageUrl: '../../assets/cards/fruits/strawberry.png',
      audioSrc: '../../../assets/audio/fruits/Strawberry.mp3',
    },
    {
      categoryId: 9,
      name: 'Raspberry',
      translation: 'ჟოლო',
      imageUrl: '../../assets/cards/fruits/raspberry.png',
      audioSrc: '../../../assets/audio/fruits/Raspberry.mp3',
    },
    {
      categoryId: 9,
      name: 'Blueberry',
      translation: 'მოცვი',
      imageUrl: '../../assets/cards/fruits/blueberry.png',
      audioSrc: '../../../assets/audio/fruits/Blueberry.mp3',
    },
    {
      categoryId: 9,
      name: 'Plum',
      translation: 'ქლიავი',
      imageUrl: '../../assets/cards/fruits/plum.png',
      audioSrc: '../../../assets/audio/fruits/Plum.mp3',
    },
    {
      categoryId: 9,
      name: 'Pineapple',
      translation: 'ანანასი',
      imageUrl: '../../assets/cards/fruits/pineapple.png',
      audioSrc: '../../../assets/audio/fruits/Pineapple.mp3',
    },
    {
      categoryId: 9,
      name: 'Kiwi',
      translation: 'კივი',
      imageUrl: '../../assets/cards/fruits/kiwi.png',
      audioSrc: '../../../assets/audio/fruits/Kiwi.mp3',
    },
    {
      categoryId: 9,
      name: 'Lime',
      translation: 'ლაიმი',
      imageUrl: '../../assets/cards/fruits/lime.png',
      audioSrc: '../../../assets/audio/fruits/Lime.mp3',
    },
    // Vegetables
    {
      categoryId: 10,
      name: 'Potato',
      translation: 'კარტოფილი',
      imageUrl: '../../assets/cards/vegetables/potato.png',
      audioSrc: '../../../assets/audio/vegetables/Potato.mp3',
    },
    {
      categoryId: 10,
      name: 'Tomato',
      translation: 'პომიდორი',
      imageUrl: '../../assets/cards/vegetables/tomato.png',
      audioSrc: '../../../assets/audio/vegetables/Tomato.mp3',
    },
    {
      categoryId: 10,
      name: 'Carrot',
      translation: 'სტაფილო',
      imageUrl: '../../assets/cards/vegetables/carrot.png',
      audioSrc: '../../../assets/audio/vegetables/Carrot.mp3',
    },
    {
      categoryId: 10,
      name: 'Radish',
      translation: 'ბოლოკი',
      imageUrl: '../../assets/cards/vegetables/radish.png',
      audioSrc: '../../../assets/audio/vegetables/Radish.mp3',
    },
    {
      categoryId: 10,
      name: 'Zucchini',
      translation: 'ყაბაყი',
      imageUrl: '../../assets/cards/vegetables/zucchini.png',
      audioSrc: '../../../assets/audio/vegetables/Zucchini.mp3',
    },
    {
      categoryId: 10,
      name: 'Cucumber',
      translation: 'კიტრი',
      imageUrl: '../../assets/cards/vegetables/cucumber.png',
      audioSrc: '../../../assets/audio/vegetables/Cucumber.mp3',
    },
    {
      categoryId: 10,
      name: 'Celery',
      translation: 'ნიახური',
      imageUrl: '../../assets/cards/vegetables/celery.png',
      audioSrc: '../../../assets/audio/vegetables/Celery.mp3',
    },
    {
      categoryId: 10,
      name: 'Broccoli',
      translation: 'ბროკოლი',
      imageUrl: '../../assets/cards/vegetables/broccoli.png',
      audioSrc: '../../../assets/audio/vegetables/Broccoli.mp3',
    },
    {
      categoryId: 10,
      name: 'Cabbage',
      translation: 'კომბოსტო',
      imageUrl: '../../assets/cards/vegetables/cabbage.png',
      audioSrc: '../../../assets/audio/vegetables/Cabbage.mp3',
    },
    {
      categoryId: 10,
      name: 'Pumpkin',
      translation: 'გოგრა',
      imageUrl: '../../assets/cards/vegetables/pumpkin.png',
      audioSrc: '../../../assets/audio/vegetables/Pumpkin.mp3',
    },
    {
      categoryId: 10,
      name: 'Onion',
      translation: 'ხახვი',
      imageUrl: '../../assets/cards/vegetables/onion.png',
      audioSrc: '../../../assets/audio/vegetables/Onion.mp3',
    },
    {
      categoryId: 10,
      name: 'Eggplant',
      translation: 'ბადრიჯანი',
      imageUrl: '../../assets/cards/vegetables/eggplant.png',
      audioSrc: '../../../assets/audio/vegetables/Eggplant.mp3',
    },
    {
      categoryId: 10,
      name: 'Garlic',
      translation: 'ნიორი',
      imageUrl: '../../assets/cards/vegetables/garlic.png',
      audioSrc: '../../../assets/audio/vegetables/Garlic.mp3',
    },
    {
      categoryId: 10,
      name: 'Bell Pepper',
      translation: 'ბულგარული წიწაკა',
      imageUrl: '../../assets/cards/vegetables/sweet-pepper.png',
      audioSrc: '../../../assets/audio/vegetables/Bell Pepper.mp3',
    },
    {
      categoryId: 10,
      name: 'Mushroom',
      translation: 'სოკო',
      imageUrl: '../../assets/cards/vegetables/mushroom.png',
      audioSrc: '../../../assets/audio/vegetables/Mushroom.mp3',
    },
    // Forms
    {
      categoryId: 11,
      name: 'Circle',
      translation: 'წრე',
      imageUrl: '../../assets/cards/forms/circle.png',
      audioSrc: '../../../assets/audio/forms/Circle.mp3',
    },
    {
      categoryId: 11,
      name: 'Oval',
      translation: 'ოვალი',
      imageUrl: '../../assets/cards/forms/oval.png',
      audioSrc: '../../../assets/audio/forms/Oval.mp3',
    },
    {
      categoryId: 11,
      name: 'Triangle',
      translation: 'სამკუთხედი',
      imageUrl: '../../assets/cards/forms/triangle.png',
      audioSrc: '../../../assets/audio/forms/Triangle.mp3',
    },
    {
      categoryId: 11,
      name: 'Rectangle',
      translation: 'მართკუთხედი',
      imageUrl: '../../assets/cards/forms/rectangle.png',
      audioSrc: '../../../assets/audio/forms/Rectangle.mp3',
    },
    {
      categoryId: 11,
      name: 'Rhombus',
      translation: 'რომბი',
      imageUrl: '../../assets/cards/forms/rhombus.png',
      audioSrc: '../../../assets/audio/forms/Rhombus.mp3',
    },
    // Space
    {
      categoryId: 12,
      name: 'Sun',
      translation: 'მზე',
      imageUrl: '../../assets/cards/space/sun.png',
      audioSrc: '../../../assets/audio/space/Sun.mp3',
    },
    {
      categoryId: 12,
      name: 'Solar System',
      translation: 'მზის სისტემა',
      imageUrl: '../../assets/cards/space/solar-system.png',
      audioSrc: '../../../assets/audio/space/Solar System.mp3',
    },
    {
      categoryId: 12,
      name: 'Mercury',
      translation: 'მერკური',
      imageUrl: '../../assets/cards/space/mercury.png',
      audioSrc: '../../../assets/audio/space/Mercury.mp3',
    },
    {
      categoryId: 12,
      name: 'Venus',
      translation: 'ვენერა',
      imageUrl: '../../assets/cards/space/venus.png',
      audioSrc: '../../../assets/audio/space/Venus.mp3',
    },
    {
      categoryId: 12,
      name: 'Earth',
      translation: 'დედამიწა',
      imageUrl: '../../assets/cards/space/earth.png',
      audioSrc: '../../../assets/audio/space/Earth.mp3',
    },
    {
      categoryId: 12,
      name: 'Mars',
      translation: 'მარსი',
      imageUrl: '../../assets/cards/space/mars.png',
      audioSrc: '../../../assets/audio/space/Mars.mp3',
    },
    {
      categoryId: 12,
      name: 'Jupiter',
      translation: 'იუპიტერი',
      imageUrl: '../../assets/cards/space/jupiter.png',
      audioSrc: '../../../assets/audio/space/Jupiter.mp3',
    },
    {
      categoryId: 12,
      name: 'Saturn',
      translation: 'სატურნი',
      imageUrl: '../../assets/cards/space/saturn.png',
      audioSrc: '../../../assets/audio/space/Saturn.mp3',
    },
    {
      categoryId: 12,
      name: 'Uranus',
      translation: 'ურანი',
      imageUrl: '../../assets/cards/space/uranus.png',
      audioSrc: '../../../assets/audio/space/Uranus.mp3',
    },
    {
      categoryId: 12,
      name: 'Neptune',
      translation: 'ნეპტუნი',
      imageUrl: '../../assets/cards/space/neptune.png',
      audioSrc: '../../../assets/audio/space/Neptune.mp3',
    },
    {
      categoryId: 12,
      name: 'Pluto',
      translation: 'პლუტონი',
      imageUrl: '../../assets/cards/space/pluto.png',
      audioSrc: '../../../assets/audio/space/Pluto.mp3',
    },
    {
      categoryId: 12,
      name: 'Moon',
      translation: 'მთვარე',
      imageUrl: '../../assets/cards/space/moon.png',
      audioSrc: '../../../assets/audio/space/Moon.mp3',
    },
    {
      categoryId: 12,
      name: 'Constellation',
      translation: 'თანავარსკლავედი',
      imageUrl: '../../assets/cards/space/constellation.png',
      audioSrc: '../../../assets/audio/space/Constellation.mp3',
    },
    {
      categoryId: 12,
      name: 'Telescope',
      translation: 'ტელესკოპი',
      imageUrl: '../../assets/cards/space/telescope.png',
      audioSrc: '../../../assets/audio/space/Telescope.mp3',
    },
    {
      categoryId: 12,
      name: 'Space Shuttle',
      translation: 'კოსმოსური ხომალდი',
      imageUrl: '../../assets/cards/space/space-shuttle.png',
      audioSrc: '../../../assets/audio/space/Space Shuttle.mp3',
    },
    {
      categoryId: 12,
      name: 'Black Hole',
      translation: 'შავი ხვრელი',
      imageUrl: '../../assets/cards/space/black-hole.png',
      audioSrc: '../../../assets/audio/space/Black Hole.mp3',
    },
    // Transport
    {
      categoryId: 13,
      name: 'Car',
      translation: 'მანქანა',
      imageUrl: '../../assets/cards/transport/car.png',
      audioSrc: '../../../assets/audio/transport/Car.mp3',
    },
    {
      categoryId: 13,
      name: 'Taxi',
      translation: 'ტაქსი',
      imageUrl: '../../assets/cards/transport/taxi.png',
      audioSrc: '../../../assets/audio/transport/Taxi.mp3',
    },
    {
      categoryId: 13,
      name: 'Bus',
      translation: 'ავტობუსი',
      imageUrl: '../../assets/cards/transport/bus.png',
      audioSrc: '../../../assets/audio/transport/Bus.mp3',
    },
    {
      categoryId: 13,
      name: 'Bicycle',
      translation: 'ველოსიპედი',
      imageUrl: '../../assets/cards/transport/bicycle.png',
      audioSrc: '../../../assets/audio/transport/Bicycle.mp3',
    },
    {
      categoryId: 13,
      name: 'Motorcycle',
      translation: 'მოტოციკლი',
      imageUrl: '../../assets/cards/transport/motorcycle.png',
      audioSrc: '../../../assets/audio/transport/Motorcycle.mp3',
    },
    {
      categoryId: 13,
      name: 'Scooter',
      translation: 'სკუტერი',
      imageUrl: '../../assets/cards/transport/scooter.png',
      audioSrc: '../../../assets/audio/transport/Scooter.mp3',
    },
    {
      categoryId: 13,
      name: 'Funicular',
      translation: 'ფუნიკულიორი',
      imageUrl: '../../assets/cards/transport/funicular.png',
      audioSrc: '../../../assets/audio/transport/Funicular.mp3',
    },
    {
      categoryId: 13,
      name: 'Train',
      translation: 'მატარებელი',
      imageUrl: '../../assets/cards/transport/train.png',
      audioSrc: '../../../assets/audio/transport/Train.mp3',
    },
    {
      categoryId: 13,
      name: 'Tractor',
      translation: 'ტრაქტორი',
      imageUrl: '../../assets/cards/transport/tractor.png',
      audioSrc: '../../../assets/audio/transport/Tractor.mp3',
    },
    {
      categoryId: 13,
      name: 'Plane',
      translation: 'თვითმფრინავი',
      imageUrl: '../../assets/cards/transport/plane.png',
      audioSrc: '../../../assets/audio/transport/Plane.mp3',
    },
    {
      categoryId: 13,
      name: 'Boat',
      translation: 'ნავი',
      imageUrl: '../../assets/cards/transport/boat.png',
      audioSrc: '../../../assets/audio/transport/Boat.mp3',
    },
    {
      categoryId: 13,
      name: 'Ship',
      translation: 'გემი',
      imageUrl: '../../assets/cards/transport/ship.png',
      audioSrc: '../../../assets/audio/transport/Ship.mp3',
    },
  ];

  constructor() {}
  public getCards(categoryId: number): any[] {
    return this.gameCards.filter((card) => card.categoryId === categoryId);
  }
  public getReverseCards(categoryId: number): any[] {
    return this.gameCards.filter((card) => card.categoryId === categoryId);
  }
}
